server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mvc?characterEncoding=UTF-8
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: utf-8
      enabled: true

### MyBatis 配置 ##########
mybatis:
  mapper-locations: classpath:mapper/*.xml