-- MySQL Script generated by MySQL Workbench
-- Sun Sep 30 13:56:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mvc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mvc` ;

-- -----------------------------------------------------
-- Schema mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvc` DEFAULT CHARACTER SET utf8 ;
USE `mvc` ;

-- -----------------------------------------------------
-- Table `mvc`.`mvc_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mvc`.`mvc_user` ;

CREATE TABLE IF NOT EXISTS `mvc`.`mvc_user` (
  `id` INT NOT NULL DEFAULT 0 COMMENT '主键id',
  `account` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '登录账号',
  `password` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '登录密码',
  `display_name` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '显示名称',
  `discription` VARCHAR(200) NOT NULL DEFAULT '' COMMENT '个人信息',
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据更新时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户基本信息';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
